### ISSUE TITLE
Error 500 on Points Settings Page

### ISSUE THREAD

**Issue by trainmania100** [dmzx/Ultimate-Points-Extension#2]
Hi
I am getting Error 500 Internal Server Error when accessing the Points Settings page under extensions.
All other ACP pages for UltimatePoints works fine.
I'm using PHPbb 3.2.2 and had no problems installing.

I am getting the following Error in apache log.

`
[Mon Apr 30 10:50:26.624995 2018] [:error] [pid 9988] [client 5.68.73.5:56614] PHP Fatal error:  Uncaught phpbb\\exception\\version_check_exception: VERSIONCHECK_FAIL in /var/www/html/phpBB3/phpbb/version_helper.php:406\nStack trace:\n#0 /var/www/html/phpBB3/phpbb/version_helper.php(354): phpbb\\version_helper->get_versions(true, false)\n#1 /var/www/html/phpBB3/phpbb/version_helper.php(333): phpbb\\version_helper->get_versions_matching_stability(true, false)\n#2 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/includes/version_check.php(67): phpbb\\version_helper->get_suggested_updates(true)\n#3 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/controller/admin_controller.php(531): dmzx\\ultimatepoints\\includes\\version_check->check()\n#4 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/acp/acp_ultimatepoints_module.php(41): dmzx\\ultimatepoints\\controller\\admin_controller->display_points()\n#5 /var/www/html/phpBB3/includes/functions_module.php(676): dmzx\\ultimatepoints\\acp\\acp_ultimatepoints_module->main('\\\\dmzx\\\\ultimatep...', 'points')\n#6 /var/www/html/phpBB3/adm/index.php(82): p_master->load_active()\n#7 {main}\n  thrown in /var/www/html/phpBB3/phpbb/version_helper.php on line 406, referer: https://www.game-station-forum.com/adm/index.php?sid=ae2fbd994650bc44b62af9b161539d89&i=32
[Mon Apr 30 10:51:53.610653 2018] [:error] [pid 9988] [client 5.68.73.5:56626] PHP Fatal error:  Uncaught phpbb\\exception\\version_check_exception: VERSIONCHECK_FAIL in /var/www/html/phpBB3/phpbb/version_helper.php:406\nStack trace:\n#0 /var/www/html/phpBB3/phpbb/version_helper.php(354): phpbb\\version_helper->get_versions(true, false)\n#1 /var/www/html/phpBB3/phpbb/version_helper.php(333): phpbb\\version_helper->get_versions_matching_stability(true, false)\n#2 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/includes/version_check.php(67): phpbb\\version_helper->get_suggested_updates(true)\n#3 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/controller/admin_controller.php(531): dmzx\\ultimatepoints\\includes\\version_check->check()\n#4 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/acp/acp_ultimatepoints_module.php(41): dmzx\\ultimatepoints\\controller\\admin_controller->display_points()\n#5 /var/www/html/phpBB3/includes/functions_module.php(676): dmzx\\ultimatepoints\\acp\\acp_ultimatepoints_module->main('\\\\dmzx\\\\ultimatep...', 'points')\n#6 /var/www/html/phpBB3/adm/index.php(82): p_master->load_active()\n#7 {main}\n  thrown in /var/www/html/phpBB3/phpbb/version_helper.php on line 406, referer: https://www.game-station-forum.com/adm/index.php?i=-dmzx-ultimatepoints-acp-acp_ultimatepoints_module&mode=forumpoints&sid=ae2fbd994650bc44b62af9b161539d89&confirm_key=3H5POMPAAG
[Mon Apr 30 10:51:56.122532 2018] [:error] [pid 8505] [client 5.68.73.5:56627] PHP Fatal error:  Uncaught phpbb\\exception\\version_check_exception: VERSIONCHECK_FAIL in /var/www/html/phpBB3/phpbb/version_helper.php:406\nStack trace:\n#0 /var/www/html/phpBB3/phpbb/version_helper.php(354): phpbb\\version_helper->get_versions(true, false)\n#1 /var/www/html/phpBB3/phpbb/version_helper.php(333): phpbb\\version_helper->get_versions_matching_stability(true, false)\n#2 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/includes/version_check.php(67): phpbb\\version_helper->get_suggested_updates(true)\n#3 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/controller/admin_controller.php(531): dmzx\\ultimatepoints\\includes\\version_check->check()\n#4 /var/www/html/phpBB3/ext/dmzx/ultimatepoints/acp/acp_ultimatepoints_module.php(41): dmzx\\ultimatepoints\\controller\\admin_controller->display_points()\n#5 /var/www/html/phpBB3/includes/functions_module.php(676): dmzx\\ultimatepoints\\acp\\acp_ultimatepoints_module->main('\\\\dmzx\\\\ultimatep...', 'points')\n#6 /var/www/html/phpBB3/adm/index.php(82): p_master->load_active()\n#7 {main}\n  thrown in /var/www/html/phpBB3/phpbb/version_helper.php on line 406
`

Any help much appreciated.

**Comment by dmzx** [comment]
check the ultimate point 3.2 version here https://www.dmzx-web.net/viewtopic.php?f=66&t=2415
