### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by jan-2017** [dmzx/Ultimate-Points-Extension#7]
Transfer is disabled in the user permission in acp, but the transfer link still appears in the profile.You can also click on the link and get to the transfer control panel.Bye Jan

**Comment by dmzx** [comment]
yes Jan I see will be fixed!

**Comment by jan-2017** [comment]
Thanks for the changing, with the update to 1.2.1. it works now. Now a normal User can not see the transfer button. Greeting Jan
